// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: string;
};

/**
 * ---------------------------------------------------------
 * SetCommentLike - 点赞/取消点赞评论（幂等操作）
 * ---------------------------------------------------------
 */
export type CommentServiceSetCommentLikeBody = {
    /**
     * true=点赞, false=取消点赞
     */
    is_liked?: boolean;
};

/**
 * ---------------------------------------------------------
 * 编辑帖子
 */
export type PostServiceEditPostBody = {
    cover?: V1Media;
    media?: Array<V1Media>;
    title?: string;
    content?: string;
    partition_id?: string;
    /**
     * 字段掩码，用于指定本次请求需要更新哪些字段
     * 例如：paths: ["title", "content"]
     */
    update_mask?: string;
};

/**
 * ---------------------------------------------------------
 * 收藏/取消收藏
 */
export type PostServiceSetPostCollectBody = {
    /**
     * true=收藏, false=取消收藏
     */
    is_collected?: boolean;
};

/**
 * ---------------------------------------------------------
 * 点赞/取消点赞
 */
export type PostServiceSetPostLikeBody = {
    /**
     * true=点赞, false=取消点赞
     */
    is_liked?: boolean;
};

/**
 * ---------------------------------------------------------
 * 封禁内容（管理员）
 */
export type ReportServiceApprovalReportBody = {
    /**
     * 封禁/删除原因
     */
    approval_reason?: string;
    ban_duration?: V1BanDurationType;
};

/**
 * ---------------------------------------------------------
 * 驳回举报（管理员）
 */
export type ReportServiceRejectReportBody = {
    [key: string]: unknown;
};

/**
 * ---------------------------------------------------------
 * 修改备注
 */
export type UserServiceChangeRemarkBody = {
    /**
     * 新的备注
     */
    remark?: string;
};

/**
 * ---------------------------------------------------------
 * 关注/取关
 */
export type UserServiceSetFollowBody = {
    /**
     * true=关注, false=取关
     */
    is_following?: boolean;
};

export type ProtobufAny = {
    '@type'?: string;
    [key: string]: unknown | string | undefined;
};

export type RpcStatus = {
    code?: number;
    message?: string;
    details?: Array<ProtobufAny>;
};

export type V1ActiveDevice = {
    /**
     * 设备 ID
     */
    device_id?: string;
    /**
     * 设备名称
     */
    device_name?: string;
    /**
     * 平台
     */
    platform?: string;
    /**
     * 连接时间
     */
    connected_at?: string;
    /**
     * 最后活跃时间
     */
    last_active_at?: string;
    /**
     * 是否为当前设备
     */
    is_current?: boolean;
};

/**
 * ---------------------------------------------------------
 * 申请身份认证
 */
export type V1ApplyVerificationRequest = {
    /**
     * 申请的认证头衔 (如: 23届部长, 社团负责人)
     */
    verified_title?: string;
    /**
     * 申请说明 (如: 申请理由、相关经历等)
     */
    verification_description?: string;
    /**
     * 证明材料
     */
    media?: Array<V1Media>;
};

export type V1ApplyVerificationResponse = {
    [key: string]: unknown;
};

export type V1ApprovalReportResponse = {
    [key: string]: unknown;
};

/**
 * ---------------------------------------------------------
 * 封禁用户时间枚举
 *
 * - BAN_DURATION_TYPE_UNSPECIFIED: 未指定
 * - BAN_DURATION_TYPE_ONE_DAY: 一天
 * - BAN_DURATION_TYPE_ONE_WEEK: 一周
 * - BAN_DURATION_TYPE_ONE_MONTH: 一月
 * - BAN_DURATION_TYPE_PERMANENT: 永久封禁
 */
export type V1BanDurationType = 'BAN_DURATION_TYPE_UNSPECIFIED' | 'BAN_DURATION_TYPE_ONE_DAY' | 'BAN_DURATION_TYPE_ONE_WEEK' | 'BAN_DURATION_TYPE_ONE_MONTH' | 'BAN_DURATION_TYPE_PERMANENT';

export type V1BasePrivacyLevel = 'BASE_PRIVACY_LEVEL_PUBLIC' | 'BASE_PRIVACY_LEVEL_PRIVATE';

/**
 * ---------------------------------------------------------
 * 修改头像
 */
export type V1ChangeAvatarRequest = {
    /**
     * 新的头像URL
     */
    avatar_url?: string;
};

export type V1ChangeAvatarResponse = {
    [key: string]: unknown;
};

/**
 * ---------------------------------------------------------
 * 修改昵称
 */
export type V1ChangeNameRequest = {
    /**
     * 新的昵称
     */
    name?: string;
};

export type V1ChangeNameResponse = {
    [key: string]: unknown;
};

export type V1ChangeRemarkResponse = {
    [key: string]: unknown;
};

export type V1ChatPrivacyLevel = 'CHAT_PRIVACY_LEVEL_PUBLIC' | 'CHAT_PRIVACY_LEVEL_FOLLOWERS' | 'CHAT_PRIVACY_LEVEL_MUTUAL' | 'CHAT_PRIVACY_LEVEL_PRIVATE';

/**
 * ---------------------------------------------------------
 * 评论完整信息（用于评论详情）
 * 说明：Comment 统一表示评论和回复，通过 parent_comment_id 区分：
 * - parent_comment_id == null  → 第一层评论（对帖子的直接评论）
 * - parent_comment_id != null  → 第二层回复（对评论的回复）
 */
export type V1Comment = {
    /**
     * 评论ID
     */
    comment_id?: string;
    /**
     * 被评论对象的ID（如帖子ID）
     */
    target_id?: string;
    target_type?: V1CommentTargetType;
    author?: V1UserBrief;
    /**
     * 评论内容（最多 300 字）
     */
    content?: string;
    /**
     * 评论附带的媒体（图片，最多 6 张）
     */
    media?: Array<V1Media>;
    stats?: V1CommentStats;
    relation_status?: V1CommentRelationStatus;
    reply_context?: V1ReplyContext;
    /**
     * 创建时间（秒级时间戳）
     */
    create_time?: string;
};

/**
 * ---------------------------------------------------------
 * 评论排序方式
 *
 * - COMMENT_ORDER_TYPE_UNSPECIFIED: 未指定（默认使用 LATEST）
 * - COMMENT_ORDER_TYPE_LATEST: --- 按时间排序 ---
 *
 * 最新评论（按创建时间降序）
 * - COMMENT_ORDER_TYPE_EARLIEST: 最早评论（按创建时间升序）
 * - COMMENT_ORDER_TYPE_MOST_LIKED: --- 按点赞数排序 ---
 *
 * 最多点赞（按点赞数降序）
 * - COMMENT_ORDER_TYPE_LEAST_LIKED: 最少点赞（按点赞数升序）
 * - COMMENT_ORDER_TYPE_MOST_REPLIES: --- 按回复数排序（仅第一层评论有效） ---
 *
 * 最多回复（按回复数降序）
 * - COMMENT_ORDER_TYPE_LEAST_REPLIES: 最少回复（按回复数升序）
 */
export type V1CommentOrderType = 'COMMENT_ORDER_TYPE_UNSPECIFIED' | 'COMMENT_ORDER_TYPE_LATEST' | 'COMMENT_ORDER_TYPE_EARLIEST' | 'COMMENT_ORDER_TYPE_MOST_LIKED' | 'COMMENT_ORDER_TYPE_LEAST_LIKED' | 'COMMENT_ORDER_TYPE_MOST_REPLIES' | 'COMMENT_ORDER_TYPE_LEAST_REPLIES';

/**
 * ---------------------------------------------------------
 * 当前用户与评论的关系状态
 */
export type V1CommentRelationStatus = {
    /**
     * 是否已点赞
     */
    is_liked?: boolean;
};

/**
 * ---------------------------------------------------------
 * 评论统计数据
 */
export type V1CommentStats = {
    /**
     * 点赞数
     */
    like_count?: string;
    /**
     * 回复数（仅第一层评论有意义）
     */
    reply_count?: string;
};

/**
 * ---------------------------------------------------------
 * 评论目标类型枚举（为未来扩展预留）
 *
 * - COMMENT_TARGET_TYPE_UNSPECIFIED: 未指定
 * - COMMENT_TARGET_TYPE_POST: 帖子
 */
export type V1CommentTargetType = 'COMMENT_TARGET_TYPE_UNSPECIFIED' | 'COMMENT_TARGET_TYPE_POST';

/**
 * ---------------------------------------------------------
 * 第一层评论 + 第一条回复的组合结构
 */
export type V1CommentWithFirstReply = {
    comment?: V1Comment;
    first_reply?: V1Comment;
    /**
     * 第一条回复的分页游标（如果存在，用于获取更多回复；如果不存在，则表示没有更多回复）
     */
    first_reply_cursor?: string;
};

/**
 * ---------------------------------------------------------
 * CreateComment - 创建评论
 * ---------------------------------------------------------
 */
export type V1CreateCommentRequest = {
    /**
     * 被评论对象的ID（如帖子ID）
     */
    target_id?: string;
    target_type?: V1CommentTargetType;
    /**
     * 评论内容（最多 300 字）
     */
    content?: string;
    /**
     * 评论附带的媒体（图片，最多 6 张）
     */
    media?: Array<V1Media>;
    reply_context?: V1ReplyContext;
};

export type V1CreateCommentResponse = {
    comment?: V1Comment;
};

/**
 * ---------------------------------------------------------
 * 发布帖子
 */
export type V1CreatePostRequest = {
    cover?: V1Media;
    media?: Array<V1Media>;
    title?: string;
    content?: string;
    partition_id?: string;
};

export type V1CreatePostResponse = {
    [key: string]: unknown;
};

/**
 * --------------------
 * 分页模型
 * 基于游标的分页模型
 */
export type V1CursorPagination = {
    /**
     * 需要返回的帖子数量
     */
    need_num?: number;
    /**
     * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
     * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
     * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
     *
     * 为空则说明是首次请求第一页数据
     */
    cursor?: string;
};

/**
 * 空响应
 */
export type V1DeleteCommentResponse = {
    [key: string]: unknown;
};

export type V1DeletePostResponse = {
    [key: string]: unknown;
};

/**
 * --------------------
 * 部门数据，用于：用户徽章渲染
 */
export type V1DepartmentBase = {
    /**
     * ID
     */
    id?: string;
    /**
     * 全称 (如 "轻音部")
     */
    name?: string;
};

export type V1DeviceInfo = {
    /**
     * 唯一设备 ID (如 UUID 或 厂商自生成 ID)
     */
    device_id?: string;
    /**
     * 设备名 (e.g. "iPhone 14 Pro")
     */
    device_name?: string;
    platform?: V1DevicePlatform;
    /**
     * 系统版本 (e.g. "iOS 16.0")
     */
    os_version?: string;
    /**
     * App/前端版本号
     */
    client_version?: string;
    /**
     * 推送 Token (FCM/APNS/MiPush)
     */
    push_token?: string;
};

export type V1DevicePlatform = 'DEVICE_PLATFORM_UNSPECIFIED' | 'DEVICE_PLATFORM_IOS' | 'DEVICE_PLATFORM_ANDROID' | 'DEVICE_PLATFORM_WEB';

/**
 * 断开指定设备连接响应
 */
export type V1DisconnectDeviceResponse = {
    /**
     * 是否成功
     */
    success?: boolean;
};

/**
 * ---------------------------------------------------------
 * 编辑个人链接
 */
export type V1EditLinksRequest = {
    /**
     * 个人链接
     */
    links?: Array<V1Link>;
};

export type V1EditLinksResponse = {
    [key: string]: unknown;
};

export type V1EditPostResponse = {
    [key: string]: unknown;
};

/**
 * Feed分类（用于button group）
 */
export type V1FeedCategory = {
    /**
     * 分类ID，可以是："general", "following", "user_tab", 或分区ID
     */
    category_id?: string;
    /**
     * 显示名称："综合"、"关注"、"用户"、或分区名称
     */
    display_name?: string;
    content_type?: V1FeedContentType;
    /**
     * 排序权重（用户可自定义）
     */
    sort_order?: number;
    /**
     * 是否为系统内置分类（如"综合"、"关注"、"用户"）
     */
    is_system?: boolean;
    /**
     * 可选的图标URL或名称
     */
    icon?: string;
};

/**
 * Feed内容类型
 *
 * - FEED_CONTENT_TYPE_POST: 帖子流
 * - FEED_CONTENT_TYPE_USER: 用户流
 * - FEED_CONTENT_TYPE_FOLLOWING_AUTHOR: 关注的作者列表（带更新状态）
 */
export type V1FeedContentType = 'FEED_CONTENT_TYPE_UNSPECIFIED' | 'FEED_CONTENT_TYPE_POST' | 'FEED_CONTENT_TYPE_USER' | 'FEED_CONTENT_TYPE_FOLLOWING_AUTHOR';

/**
 * Feed过滤器（整合post和user的filter）
 */
export type V1FeedFilter = {
    /**
     * 关键词搜索
     */
    keyword?: string;
    time_range?: V1TimeRange;
    order_type?: V1FeedOrderType;
    /**
     * 作者ID筛选（仅帖子流，配合"following"场景使用）
     */
    author_id?: string;
};

/**
 * Feed排序类型（统一的排序枚举）
 *
 * - FEED_ORDER_TYPE_RECOMMENDED: 推荐排序（帖子/用户通用）
 * - FEED_ORDER_TYPE_LATEST: 最新排序（仅帖子）
 * - FEED_ORDER_TYPE_HOT: 热门排序（仅帖子）
 * - FEED_ORDER_TYPE_MOST_FOLLOWERS: 最多粉丝（仅用户）
 * - FEED_ORDER_TYPE_LEAST_FOLLOWER: 最少粉丝（仅用户）
 * - FEED_ORDER_TYPE_MOST_INTERACTIONS: 最多互动（仅用户）
 * - FEED_ORDER_TYPE_LEAST_INTERACTIONS: 最少互动（仅用户）
 */
export type V1FeedOrderType = 'FEED_ORDER_TYPE_UNSPECIFIED' | 'FEED_ORDER_TYPE_RECOMMENDED' | 'FEED_ORDER_TYPE_LATEST' | 'FEED_ORDER_TYPE_HOT' | 'FEED_ORDER_TYPE_MOST_FOLLOWERS' | 'FEED_ORDER_TYPE_LEAST_FOLLOWER' | 'FEED_ORDER_TYPE_MOST_INTERACTIONS' | 'FEED_ORDER_TYPE_LEAST_INTERACTIONS';

/**
 * ---------------------------------------------------------
 * 推荐关注作者列表
 */
export type V1FollowingAuthor = {
    author?: V1UserBrief;
    /**
     * 有未读更新
     */
    has_unread?: boolean;
};

/**
 * 关注的作者流内容（用于关注页顶部的横向滚动列表）
 */
export type V1FollowingAuthorFeedContent = {
    items?: Array<V1FollowingAuthor>;
};

/**
 * 强制同步请求（主动触发全量同步）
 */
export type V1ForceSyncRequest = {
    /**
     * 要同步的数据类型，空表示全部
     */
    sync_types?: Array<V1SyncDataType>;
};

/**
 * 强制同步响应
 */
export type V1ForceSyncResponse = {
    /**
     * 是否成功
     */
    success?: boolean;
    /**
     * 消息
     */
    message?: string;
};

/**
 * 获取活跃设备列表响应
 */
export type V1GetActiveDevicesResponse = {
    /**
     * 活跃设备列表
     */
    devices?: Array<V1ActiveDevice>;
};

export type V1GetFeedResponse = {
    content_type?: V1FeedContentType;
    posts?: V1PostFeedContent;
    users?: V1UserFeedContent;
    following_authors?: V1FollowingAuthorFeedContent;
    /**
     * 分页游标
     */
    cursor?: string;
};

export type V1GetMeResponse = {
    profile?: V1UserProfile;
    settings?: V1SyncedUserSettings;
};

export type V1GetMyVerificationResponse = {
    application?: V1VerificationApplication;
};

export type V1GetPostResponse = {
    post?: V1Post;
};

/**
 * 获取同步状态响应
 */
export type V1GetSyncStatusResponse = {
    status?: V1SyncStatus;
};

export type V1GetUserIdByQqResponse = {
    /**
     * 用户ID
     */
    user_id?: string;
};

export type V1GetUserResponse = {
    user?: V1UserProfile;
    relation_status?: V1UserRelationStatus;
    view_capabilities?: V1UserViewCapabilities;
};

export type V1HandleReportAdmin = {
    /**
     * 处理管理员ID
     */
    admin_id?: string;
    /**
     * 处理管理员名称
     */
    admin_name?: string;
};

/**
 * --------------------
 * 外部链接结构
 */
export type V1Link = {
    /**
     * 链接显示文字
     */
    label?: string;
    /**
     * 实际跳转地址
     */
    url?: string;
};

export type V1ListCommentRepliesResponse = {
    /**
     * 第二层回复列表（打平显示）
     */
    replies?: Array<V1Comment>;
    /**
     * 下一页游标（用于加载更多第二层回复），为空则说明没有更多回复了
     */
    cursor?: string;
    /**
     * 总回复数（方便客户端显示"还有 X 条回复"）
     */
    total_count?: string;
};

export type V1ListFeedCategoriesResponse = {
    categories?: Array<V1FeedCategory>;
};

export type V1ListPostCommentsResponse = {
    /**
     * 第一层评论列表（每条自动包含第一条回复）
     */
    comments?: Array<V1CommentWithFirstReply>;
    /**
     * 下一页游标（用于加载更多第一层评论），为空则说明没有更多评论了
     */
    cursor?: string;
};

export type V1ListReportEvidenceResponse = {
    /**
     * 举报详情
     */
    report_evidence?: Array<V1ReportEvidenceItem>;
    /**
     * 下一页游标，如果没有下一页则为空
     */
    cursor?: string;
};

export type V1ListReportsResponse = {
    /**
     * 举报列表
     */
    reports?: Array<V1ReportItem>;
    /**
     * 下一页游标，如果没有下一页则为空
     */
    cursor?: string;
};

export type V1ListUserPostsResponse = {
    /**
     * 帖子列表
     */
    posts?: Array<V1PostPreview>;
    /**
     * 分页游标，如果为空则表示没有更多数据
     */
    cursor?: string;
};

export type V1ListUserRelatedResponse = {
    users?: Array<V1UserListItem>;
    /**
     * 分页游标，如果为空则表示没有更多数据
     */
    cursor?: string;
};

/**
 * ---------------------------------------------------------
 * 登录请求
 */
export type V1LoginRequest = {
    /**
     * 凭证载荷：QQ 传 AccessToken
     */
    credential?: string;
    device?: V1DeviceInfo;
};

export type V1LoginResponse = {
    /**
     * 短期令牌 (如 2小时)，过期绝对时间戳及user_id放在payload中
     */
    access_token?: string;
    /**
     * 长期令牌 (如 30天)，过期绝对时间戳放在payload中
     */
    refresh_token?: string;
    user?: V1UserSummary;
};

export type V1LogoutResponse = {
    [key: string]: unknown;
};

/**
 * --------------------
 * 媒体资源
 */
export type V1Media = {
    /**
     * 雪花 ID
     */
    id?: string;
    type?: V1MediaType;
    /**
     * 核心存储标识
     *
     * 存储桶：shining-vod
     */
    bucket?: string;
    /**
     * 对象路径：videos/2024/01/v001.m3u8
     */
    object_key?: string;
    meta?: V1MediaMeta;
    /**
     * 状态与权限
     *
     * 0:处理中, 1:就绪, 2:违规屏蔽
     */
    status?: number;
};

export type V1MediaMeta = {
    width?: number;
    height?: number;
    /**
     * 视频时长（秒）
     */
    duration?: number;
    /**
     * 文件大小（字节）
     */
    size?: string;
    /**
     * video/mp4, image/webp
     */
    mime_type?: string;
};

export type V1MediaType = 'MEDIA_TYPE_UNSPECIFIED' | 'MEDIA_TYPE_IMAGE' | 'MEDIA_TYPE_VIDEO';

/**
 * ---------------------------------------------------------
 * 修改所属部门
 */
export type V1ModifyDepartmentsRequest = {
    /**
     * 选择的部门 ID 列表
     */
    department_ids?: Array<string>;
};

export type V1ModifyDepartmentsResponse = {
    [key: string]: unknown;
};

/**
 * ---------------------------------------------------------
 * 帖子相关
 */
export type V1Post = {
    post_id?: string;
    author?: V1UserSummary;
    /**
     * 帖子标题
     */
    title?: string;
    /**
     * 帖子正文描述
     */
    content?: string;
    media?: Array<V1Media>;
    stats?: V1PostStats;
    relation_status?: V1PostRelationStatus;
    /**
     * 秒级时间戳
     */
    publish_time?: string;
    update_time?: string;
};

/**
 * 帖子流内容
 */
export type V1PostFeedContent = {
    items?: Array<V1PostPreview>;
};

/**
 * ---------------------------------------------------------
 * 帖子过滤器（用于个人资料页的帖子列表）
 */
export type V1PostFilter = {
    /**
     * 关键词搜索
     */
    keyword?: string;
};

/**
 * 帖子预览（卡片视图数据）
 */
export type V1PostPreview = {
    post_id?: string;
    /**
     * 如果用户输入了标题，则这里显示标题；如果没有输入标题，则将正文描述的前30个字作为标题传输过来；如果都没有，不传输此字段。
     */
    display_title?: string;
    cover?: V1Media;
    author?: V1UserBrief;
    stats?: V1PostStats;
    relation_status?: V1PostRelationStatus;
    /**
     * UI上是否显示一个“播放”的小图标
     */
    is_only_video?: boolean;
    /**
     * 秒级时间戳
     */
    publish_time?: string;
    update_time?: string;
};

/**
 * 当前用户与帖子的关系状态
 */
export type V1PostRelationStatus = {
    is_liked?: boolean;
    is_collected?: boolean;
};

/**
 * 帖子统计数据
 */
export type V1PostStats = {
    like_count?: string;
    collect_count?: string;
    comment_count?: string;
    view_count?: string;
};

/**
 * ---------------------------------------------------------
 * 刷新 token
 */
export type V1RefreshTokenRequest = {
    refresh_token?: string;
};

export type V1RefreshTokenResponse = {
    access_token?: string;
    /**
     * 可选：实现 RefreshToken 轮转机制时，会下发新的 RT
     */
    refresh_token?: string;
};

/**
 * --------------------
 * 刷新类型枚举
 *
 * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
 * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
 */
export type V1RefreshType = 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';

export type V1RejectReportResponse = {
    [key: string]: unknown;
};

export type V1Reply = {
    comment?: V1Comment;
    /**
     * 回复的评论摘要（截取 100 字符）
     */
    reply_to_summary?: string;
};

/**
 * ---------------------------------------------------------
 * 回复上下文（仅第二层评论有意义）
 */
export type V1ReplyContext = {
    /**
     * 层级信息（仅第二层回复时有值）
     *
     * 父评论ID（第二层回复必填，第一层评论为null）
     */
    parent_comment_id?: string;
    /**
     * 回复的评论ID（第二层回复必填，指向被回复的评论）
     */
    reply_to_comment_id?: string;
    /**
     * 回复的用户ID（第二层回复必填，用于UI显示"回复了@xxx"）
     */
    reply_to_user_id?: string;
    /**
     * 回复的用户名（第二层回复必填，冗余字段避免额外查询）
     */
    reply_to_user_name?: string;
};

/**
 * ---------------------------------------------------------
 * 举报评论
 */
export type V1ReportCommentRequest = {
    /**
     * 被举报的评论ID
     */
    comment_id?: string;
    /**
     * 评论所属的帖子ID
     */
    post_id?: string;
};

export type V1ReportCommentResponse = {
    /**
     * 举报记录ID
     */
    report_id?: string;
};

/**
 * ---------------------------------------------------------
 * 举报证据（当 ReportType 为用户时，可以展示举报者提供的举报证据）
 */
export type V1ReportEvidenceItem = {
    /**
     * 举报证据ID
     */
    report_evidence_id?: string;
    /**
     * 举报证据所属举报记录ID
     */
    report_id?: string;
    reporter?: V1UserBrief;
    /**
     * 举报说明
     */
    reason?: string;
    /**
     * 举报证据图片
     */
    media?: Array<V1Media>;
};

/**
 * ---------------------------------------------------------
 * 举报列表项（用于列表展示）
 */
export type V1ReportItem = {
    /**
     * 举报记录ID
     */
    report_id?: string;
    type?: V1ReportType;
    status?: V1ReportStatus;
    reported_user?: V1UserBrief;
    reported_post?: V1PostPreview;
    reported_comment?: V1Comment;
    reported_reply?: V1Reply;
    /**
     * 举报次数（同一对象被多次举报时的计数）
     */
    report_count?: string;
    admin?: V1HandleReportAdmin;
};

/**
 * ---------------------------------------------------------
 * 举报帖子
 */
export type V1ReportPostRequest = {
    /**
     * 被举报的帖子ID
     */
    post_id?: string;
};

export type V1ReportPostResponse = {
    /**
     * 举报记录ID
     */
    report_id?: string;
};

/**
 * ---------------------------------------------------------
 * 举报状态枚举
 *
 * - REPORT_STATUS_UNSPECIFIED: 未指定
 * - REPORT_STATUS_PENDING: 待处理
 * - REPORT_STATUS_PROCESSING: 处理中
 * - REPORT_STATUS_RESOLVED: 已处理（已采纳）
 * - REPORT_STATUS_REJECTED: 已驳回
 */
export type V1ReportStatus = 'REPORT_STATUS_UNSPECIFIED' | 'REPORT_STATUS_PENDING' | 'REPORT_STATUS_PROCESSING' | 'REPORT_STATUS_RESOLVED' | 'REPORT_STATUS_REJECTED';

/**
 * ---------------------------------------------------------
 * 举报类型枚举
 *
 * - REPORT_TYPE_UNSPECIFIED: 未指定
 * - REPORT_TYPE_USER: 举报用户
 * - REPORT_TYPE_POST: 举报帖子
 * - REPORT_TYPE_COMMENT: 举报评论
 * - REPORT_TYPE_REPLY: 举报回复
 */
export type V1ReportType = 'REPORT_TYPE_UNSPECIFIED' | 'REPORT_TYPE_USER' | 'REPORT_TYPE_POST' | 'REPORT_TYPE_COMMENT' | 'REPORT_TYPE_REPLY';

/**
 * ---------------------------------------------------------
 * 举报用户
 */
export type V1ReportUserRequest = {
    /**
     * 被举报的用户ID
     */
    user_id?: string;
    /**
     * 举报说明（必填）
     */
    reason?: string;
    /**
     * 证明材料图片ID（最多3张）
     */
    media?: Array<V1Media>;
};

export type V1ReportUserResponse = {
    /**
     * 举报记录ID
     */
    report_id?: string;
};

/**
 * 用户角色枚举
 *
 * - ROLE_VISITOR: 游客
 * - ROLE_USER: 用户
 * - ROLE_ADMIN: 内容管理员
 * - ROLE_SUPER_ADMIN: 超级管理员
 */
export type V1Role = 'ROLE_VISITOR' | 'ROLE_USER' | 'ROLE_ADMIN' | 'ROLE_SUPER_ADMIN';

export type V1SetCommentLikeResponse = {
    [key: string]: unknown;
};

export type V1SetFollowResponse = {
    [key: string]: unknown;
};

export type V1SetPostCollectResponse = {
    [key: string]: unknown;
};

export type V1SetPostLikeResponse = {
    [key: string]: unknown;
};

/**
 * - SYNC_DATA_TYPE_USER_SETTINGS: 用户设置
 * - SYNC_DATA_TYPE_NOTIFICATION_SETTINGS: 通知设置
 * - SYNC_DATA_TYPE_PRIVACY_SETTINGS: 隐私设置
 * - SYNC_DATA_TYPE_CONTENT_CATEGORY_ORDER: 内容分类排序
 */
export type V1SyncDataType = 'SYNC_DATA_TYPE_UNSPECIFIED' | 'SYNC_DATA_TYPE_USER_SETTINGS' | 'SYNC_DATA_TYPE_NOTIFICATION_SETTINGS' | 'SYNC_DATA_TYPE_PRIVACY_SETTINGS' | 'SYNC_DATA_TYPE_CONTENT_CATEGORY_ORDER';

export type V1SyncStatus = {
    /**
     * 用户 ID
     */
    user_id?: string;
    /**
     * 活跃设备列表
     */
    active_devices?: Array<V1ActiveDevice>;
    /**
     * 最后同步时间
     */
    last_sync_at?: string;
    /**
     * 各数据类型的版本号（key: SyncDataType的字符串值）
     */
    data_versions?: {
        [key: string]: string;
    };
};

export type V1SyncedContentCategoryOrder = {
    /**
     * 按用户偏好排序的内容分类ID列表
     */
    category_ids?: Array<string>;
};

/**
 * 通知设置 (仅自己可见)
 */
export type V1SyncedNotificationSettings = {
    /**
     * APP 内推送总开关
     */
    app_push_enabled?: boolean;
    /**
     * 我的消息推送
     */
    push_my_message?: boolean;
    /**
     * 评论与 @ 推送
     */
    push_comment_at?: boolean;
    /**
     * 点赞与收藏推送
     */
    push_like_collect?: boolean;
    /**
     * 新粉丝推送
     */
    push_new_follower?: boolean;
    /**
     * 晒你通知
     */
    push_shining_notification?: boolean;
    /**
     * 关注动态推送
     */
    push_post_update?: boolean;
    /**
     * 举报反馈推送
     */
    push_report?: boolean;
    /**
     * 新增身份认证申请推送
     */
    push_verification_request?: boolean;
};

/**
 * 隐私设置 (仅自己可见)
 */
export type V1SyncedPrivacySettings = {
    chat_permission?: V1ChatPrivacyLevel;
    liked_posts_visibility?: V1BasePrivacyLevel;
    collected_posts_visibility?: V1BasePrivacyLevel;
};

/**
 * ---------------------------------------------------------
 * 用户通用设置 (仅自己可见的需要多端同步的设置选项)
 */
export type V1SyncedUserSettings = {
    notification?: V1SyncedNotificationSettings;
    privacy?: V1SyncedPrivacySettings;
    content_category_order?: V1SyncedContentCategoryOrder;
};

/**
 * --------------------
 * 时间范围结构（秒级时间戳）
 */
export type V1TimeRange = {
    /**
     * 开始时间
     */
    start_timestamp?: string;
    /**
     * 结束时间
     */
    end_timestamp?: string;
};

/**
 * ---------------------------------------------------------
 * 更新 push_token
 */
export type V1UpdatePushTokenRequest = {
    /**
     * 标识是哪个设备变更了 token
     */
    device_id?: string;
    push_token?: string;
};

export type V1UpdatePushTokenResponse = {
    [key: string]: unknown;
};

/**
 * ---------------------------------------------------------
 * 更新我的设置
 */
export type V1UpdateSettingsRequest = {
    settings?: V1SyncedUserSettings;
    update_mask?: string;
};

export type V1UpdateSettingsResponse = {
    settings?: V1SyncedUserSettings;
};

/**
 * 用户数据模型
 */
export type V1UserBrief = {
    /**
     * 用户ID
     */
    user_id?: string;
    /**
     * 用户名
     */
    name?: string;
    /**
     * 用户备注
     */
    remark?: string;
    /**
     * 头像URL
     */
    avatar?: string;
    /**
     * QQ 号
     */
    qq_number?: string;
    role?: V1Role;
};

/**
 * 用户流内容
 */
export type V1UserFeedContent = {
    items?: Array<V1UserSummary>;
    relation_status?: V1UserRelationStatus;
};

/**
 * 用户筛选器设计
 */
export type V1UserFilter = {
    /**
     * 关键词搜索
     */
    keyword?: string;
};

/**
 * 用户列表数据模型设计（用于批量接口返回）
 */
export type V1UserListItem = {
    info?: V1UserBrief;
    relation_status?: V1UserRelationStatus;
};

export type V1UserProfile = {
    user_id?: string;
    name?: string;
    /**
     * 用户备注
     */
    remark?: string;
    avatar?: string;
    qq_number?: string;
    role?: V1Role;
    /**
     * 认证头衔（如：23届部长）
     */
    verified_title?: string;
    /**
     * 所所属部门
     */
    departments?: Array<V1DepartmentBase>;
    stats?: V1UserStats;
    /**
     * 外部链接
     */
    links?: Array<V1Link>;
};

/**
 * 关系状态 (仅关注关系)
 */
export type V1UserRelationStatus = {
    /**
     * 当前用户是否关注了目标用户
     */
    is_following?: boolean;
    /**
     * 目标用户是否关注了当前用户
     */
    is_followed_by?: boolean;
};

/**
 * 统计数据
 */
export type V1UserStats = {
    /**
     * 粉丝数
     */
    follower_count?: string;
    /**
     * 关注数
     */
    following_count?: string;
    /**
     * 获得的赞
     */
    like_count_received?: string;
    /**
     * 获得的收藏
     */
    collect_count_received?: string;
    /**
     * 获得浏览
     */
    view_count_received?: string;
};

export type V1UserSummary = {
    /**
     * 用户ID
     */
    user_id?: string;
    /**
     * 用户名
     */
    name?: string;
    /**
     * 用户备注
     */
    remark?: string;
    /**
     * 头像URL
     */
    avatar?: string;
    /**
     * QQ 号
     */
    qq_number?: string;
    role?: V1Role;
    /**
     * 认证头衔（如：23届部长）
     */
    verified_title?: string;
    /**
     * 所所属部门
     */
    departments?: Array<V1DepartmentBase>;
    stats?: V1UserStats;
};

/**
 * 隐私能力 (当前用户对目标用户的操作权限)
 * Critical: 不要返回 PrivacySettings，返回计算后的 Capability
 */
export type V1UserViewCapabilities = {
    /**
     * 是否可以发送私信
     */
    can_chat?: boolean;
    /**
     * 是否可以查看点赞列表
     */
    can_view_liked_posts?: boolean;
    /**
     * 是否可以查看收藏列表
     */
    can_view_collected_posts?: boolean;
};

/**
 * 认证申请详情
 */
export type V1VerificationApplication = {
    /**
     * 申请 ID
     */
    application_id?: string;
    /**
     * 申请的认证头衔
     */
    verified_title?: string;
    /**
     * 申请说明
     */
    verification_description?: string;
    /**
     * 证明材料
     */
    media?: Array<V1Media>;
    /**
     * 申请时间
     */
    applied_time?: string;
    status?: V1VerificationStatus;
};

/**
 * 认证状态枚举
 *
 * - VERIFICATION_STATUS_PENDING: 待处理
 * - VERIFICATION_STATUS_APPROVED: 已通过
 * - VERIFICATION_STATUS_REJECTED: 已拒绝
 */
export type V1VerificationStatus = 'VERIFICATION_STATUS_UNSPECIFIED' | 'VERIFICATION_STATUS_PENDING' | 'VERIFICATION_STATUS_APPROVED' | 'VERIFICATION_STATUS_REJECTED';

export type AuthServiceLoginData = {
    body: V1LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/auth';
};

export type AuthServiceLoginErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceLoginError = AuthServiceLoginErrors[keyof AuthServiceLoginErrors];

export type AuthServiceLoginResponses = {
    /**
     * A successful response.
     */
    200: V1LoginResponse;
};

export type AuthServiceLoginResponse = AuthServiceLoginResponses[keyof AuthServiceLoginResponses];

export type AuthServiceLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/logout';
};

export type AuthServiceLogoutErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceLogoutError = AuthServiceLogoutErrors[keyof AuthServiceLogoutErrors];

export type AuthServiceLogoutResponses = {
    /**
     * A successful response.
     */
    200: V1LogoutResponse;
};

export type AuthServiceLogoutResponse = AuthServiceLogoutResponses[keyof AuthServiceLogoutResponses];

export type AuthServiceUpdatePushTokenData = {
    body: V1UpdatePushTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/push-token';
};

export type AuthServiceUpdatePushTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceUpdatePushTokenError = AuthServiceUpdatePushTokenErrors[keyof AuthServiceUpdatePushTokenErrors];

export type AuthServiceUpdatePushTokenResponses = {
    /**
     * A successful response.
     */
    200: V1UpdatePushTokenResponse;
};

export type AuthServiceUpdatePushTokenResponse = AuthServiceUpdatePushTokenResponses[keyof AuthServiceUpdatePushTokenResponses];

export type AuthServiceRefreshTokenData = {
    body: V1RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh';
};

export type AuthServiceRefreshTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type AuthServiceRefreshTokenError = AuthServiceRefreshTokenErrors[keyof AuthServiceRefreshTokenErrors];

export type AuthServiceRefreshTokenResponses = {
    /**
     * A successful response.
     */
    200: V1RefreshTokenResponse;
};

export type AuthServiceRefreshTokenResponse = AuthServiceRefreshTokenResponses[keyof AuthServiceRefreshTokenResponses];

export type CommentServiceCreateCommentData = {
    body: V1CreateCommentRequest;
    path?: never;
    query?: never;
    url: '/v1/comments';
};

export type CommentServiceCreateCommentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceCreateCommentError = CommentServiceCreateCommentErrors[keyof CommentServiceCreateCommentErrors];

export type CommentServiceCreateCommentResponses = {
    /**
     * A successful response.
     */
    200: V1CreateCommentResponse;
};

export type CommentServiceCreateCommentResponse = CommentServiceCreateCommentResponses[keyof CommentServiceCreateCommentResponses];

export type CommentServiceDeleteCommentData = {
    body?: never;
    path: {
        /**
         * 评论ID
         */
        comment_id: string;
    };
    query?: never;
    url: '/v1/comments/{comment_id}';
};

export type CommentServiceDeleteCommentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceDeleteCommentError = CommentServiceDeleteCommentErrors[keyof CommentServiceDeleteCommentErrors];

export type CommentServiceDeleteCommentResponses = {
    /**
     * A successful response.
     */
    200: V1DeleteCommentResponse;
};

export type CommentServiceDeleteCommentResponse = CommentServiceDeleteCommentResponses[keyof CommentServiceDeleteCommentResponses];

export type CommentServiceSetCommentLikeData = {
    body: CommentServiceSetCommentLikeBody;
    path: {
        /**
         * 评论ID
         */
        comment_id: string;
    };
    query?: never;
    url: '/v1/comments/{comment_id}/like';
};

export type CommentServiceSetCommentLikeErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceSetCommentLikeError = CommentServiceSetCommentLikeErrors[keyof CommentServiceSetCommentLikeErrors];

export type CommentServiceSetCommentLikeResponses = {
    /**
     * A successful response.
     */
    200: V1SetCommentLikeResponse;
};

export type CommentServiceSetCommentLikeResponse = CommentServiceSetCommentLikeResponses[keyof CommentServiceSetCommentLikeResponses];

export type CommentServiceListCommentRepliesData = {
    body?: never;
    path: {
        /**
         * 第一层评论ID
         */
        comment_id: string;
    };
    query?: {
        /**
         * 排序方式（默认：最早）
         *
         * - COMMENT_ORDER_TYPE_UNSPECIFIED: 未指定（默认使用 LATEST）
         * - COMMENT_ORDER_TYPE_LATEST: --- 按时间排序 ---
         *
         * 最新评论（按创建时间降序）
         * - COMMENT_ORDER_TYPE_EARLIEST: 最早评论（按创建时间升序）
         * - COMMENT_ORDER_TYPE_MOST_LIKED: --- 按点赞数排序 ---
         *
         * 最多点赞（按点赞数降序）
         * - COMMENT_ORDER_TYPE_LEAST_LIKED: 最少点赞（按点赞数升序）
         * - COMMENT_ORDER_TYPE_MOST_REPLIES: --- 按回复数排序（仅第一层评论有效） ---
         *
         * 最多回复（按回复数降序）
         * - COMMENT_ORDER_TYPE_LEAST_REPLIES: 最少回复（按回复数升序）
         */
        order_type?: 'COMMENT_ORDER_TYPE_UNSPECIFIED' | 'COMMENT_ORDER_TYPE_LATEST' | 'COMMENT_ORDER_TYPE_EARLIEST' | 'COMMENT_ORDER_TYPE_MOST_LIKED' | 'COMMENT_ORDER_TYPE_LEAST_LIKED' | 'COMMENT_ORDER_TYPE_MOST_REPLIES' | 'COMMENT_ORDER_TYPE_LEAST_REPLIES';
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/comments/{comment_id}/replies';
};

export type CommentServiceListCommentRepliesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceListCommentRepliesError = CommentServiceListCommentRepliesErrors[keyof CommentServiceListCommentRepliesErrors];

export type CommentServiceListCommentRepliesResponses = {
    /**
     * A successful response.
     */
    200: V1ListCommentRepliesResponse;
};

export type CommentServiceListCommentRepliesResponse = CommentServiceListCommentRepliesResponses[keyof CommentServiceListCommentRepliesResponses];

export type FeedServiceGetFeedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 分类ID（来自ListFeedCategories返回的category_id）
         */
        category_id?: string;
        /**
         * 刷新类型：下拉刷新/上拉加载
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 开始时间
         */
        'filter.time_range.start_timestamp'?: string;
        /**
         * 结束时间
         */
        'filter.time_range.end_timestamp'?: string;
        /**
         * 排序方式（根据content_type自动选择合适的排序）
         *
         * - FEED_ORDER_TYPE_RECOMMENDED: 推荐排序（帖子/用户通用）
         * - FEED_ORDER_TYPE_LATEST: 最新排序（仅帖子）
         * - FEED_ORDER_TYPE_HOT: 热门排序（仅帖子）
         * - FEED_ORDER_TYPE_MOST_FOLLOWERS: 最多粉丝（仅用户）
         * - FEED_ORDER_TYPE_LEAST_FOLLOWER: 最少粉丝（仅用户）
         * - FEED_ORDER_TYPE_MOST_INTERACTIONS: 最多互动（仅用户）
         * - FEED_ORDER_TYPE_LEAST_INTERACTIONS: 最少互动（仅用户）
         */
        'filter.order_type'?: 'FEED_ORDER_TYPE_UNSPECIFIED' | 'FEED_ORDER_TYPE_RECOMMENDED' | 'FEED_ORDER_TYPE_LATEST' | 'FEED_ORDER_TYPE_HOT' | 'FEED_ORDER_TYPE_MOST_FOLLOWERS' | 'FEED_ORDER_TYPE_LEAST_FOLLOWER' | 'FEED_ORDER_TYPE_MOST_INTERACTIONS' | 'FEED_ORDER_TYPE_LEAST_INTERACTIONS';
        /**
         * 作者ID筛选（仅帖子流，配合"following"场景使用）
         */
        'filter.author_id'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/feed';
};

export type FeedServiceGetFeedErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type FeedServiceGetFeedError = FeedServiceGetFeedErrors[keyof FeedServiceGetFeedErrors];

export type FeedServiceGetFeedResponses = {
    /**
     * A successful response.
     */
    200: V1GetFeedResponse;
};

export type FeedServiceGetFeedResponse = FeedServiceGetFeedResponses[keyof FeedServiceGetFeedResponses];

export type FeedServiceListFeedCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 可选：只获取特定类型的分类
         *
         * - FEED_CONTENT_TYPE_POST: 帖子流
         * - FEED_CONTENT_TYPE_USER: 用户流
         * - FEED_CONTENT_TYPE_FOLLOWING_AUTHOR: 关注的作者列表（带更新状态）
         */
        filter_type?: 'FEED_CONTENT_TYPE_UNSPECIFIED' | 'FEED_CONTENT_TYPE_POST' | 'FEED_CONTENT_TYPE_USER' | 'FEED_CONTENT_TYPE_FOLLOWING_AUTHOR';
    };
    url: '/v1/feed/categories';
};

export type FeedServiceListFeedCategoriesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type FeedServiceListFeedCategoriesError = FeedServiceListFeedCategoriesErrors[keyof FeedServiceListFeedCategoriesErrors];

export type FeedServiceListFeedCategoriesResponses = {
    /**
     * A successful response.
     */
    200: V1ListFeedCategoriesResponse;
};

export type FeedServiceListFeedCategoriesResponse = FeedServiceListFeedCategoriesResponses[keyof FeedServiceListFeedCategoriesResponses];

export type PostServiceCreatePostData = {
    body: V1CreatePostRequest;
    path?: never;
    query?: never;
    url: '/v1/posts';
};

export type PostServiceCreatePostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceCreatePostError = PostServiceCreatePostErrors[keyof PostServiceCreatePostErrors];

export type PostServiceCreatePostResponses = {
    /**
     * A successful response.
     */
    200: V1CreatePostResponse;
};

export type PostServiceCreatePostResponse = PostServiceCreatePostResponses[keyof PostServiceCreatePostResponses];

export type PostServiceDeletePostData = {
    body?: never;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}';
};

export type PostServiceDeletePostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceDeletePostError = PostServiceDeletePostErrors[keyof PostServiceDeletePostErrors];

export type PostServiceDeletePostResponses = {
    /**
     * A successful response.
     */
    200: V1DeletePostResponse;
};

export type PostServiceDeletePostResponse = PostServiceDeletePostResponses[keyof PostServiceDeletePostResponses];

export type PostServiceGetPostData = {
    body?: never;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}';
};

export type PostServiceGetPostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceGetPostError = PostServiceGetPostErrors[keyof PostServiceGetPostErrors];

export type PostServiceGetPostResponses = {
    /**
     * A successful response.
     */
    200: V1GetPostResponse;
};

export type PostServiceGetPostResponse = PostServiceGetPostResponses[keyof PostServiceGetPostResponses];

export type PostServiceEditPostData = {
    body: PostServiceEditPostBody;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}';
};

export type PostServiceEditPostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceEditPostError = PostServiceEditPostErrors[keyof PostServiceEditPostErrors];

export type PostServiceEditPostResponses = {
    /**
     * A successful response.
     */
    200: V1EditPostResponse;
};

export type PostServiceEditPostResponse = PostServiceEditPostResponses[keyof PostServiceEditPostResponses];

export type PostServiceSetPostCollectData = {
    body: PostServiceSetPostCollectBody;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}/collection';
};

export type PostServiceSetPostCollectErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceSetPostCollectError = PostServiceSetPostCollectErrors[keyof PostServiceSetPostCollectErrors];

export type PostServiceSetPostCollectResponses = {
    /**
     * A successful response.
     */
    200: V1SetPostCollectResponse;
};

export type PostServiceSetPostCollectResponse = PostServiceSetPostCollectResponses[keyof PostServiceSetPostCollectResponses];

export type CommentServiceListPostCommentsData = {
    body?: never;
    path: {
        /**
         * 帖子ID
         */
        post_id: string;
    };
    query?: {
        /**
         * 排序方式（默认：点赞数最多）
         *
         * - COMMENT_ORDER_TYPE_UNSPECIFIED: 未指定（默认使用 LATEST）
         * - COMMENT_ORDER_TYPE_LATEST: --- 按时间排序 ---
         *
         * 最新评论（按创建时间降序）
         * - COMMENT_ORDER_TYPE_EARLIEST: 最早评论（按创建时间升序）
         * - COMMENT_ORDER_TYPE_MOST_LIKED: --- 按点赞数排序 ---
         *
         * 最多点赞（按点赞数降序）
         * - COMMENT_ORDER_TYPE_LEAST_LIKED: 最少点赞（按点赞数升序）
         * - COMMENT_ORDER_TYPE_MOST_REPLIES: --- 按回复数排序（仅第一层评论有效） ---
         *
         * 最多回复（按回复数降序）
         * - COMMENT_ORDER_TYPE_LEAST_REPLIES: 最少回复（按回复数升序）
         */
        order_type?: 'COMMENT_ORDER_TYPE_UNSPECIFIED' | 'COMMENT_ORDER_TYPE_LATEST' | 'COMMENT_ORDER_TYPE_EARLIEST' | 'COMMENT_ORDER_TYPE_MOST_LIKED' | 'COMMENT_ORDER_TYPE_LEAST_LIKED' | 'COMMENT_ORDER_TYPE_MOST_REPLIES' | 'COMMENT_ORDER_TYPE_LEAST_REPLIES';
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/posts/{post_id}/comments';
};

export type CommentServiceListPostCommentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type CommentServiceListPostCommentsError = CommentServiceListPostCommentsErrors[keyof CommentServiceListPostCommentsErrors];

export type CommentServiceListPostCommentsResponses = {
    /**
     * A successful response.
     */
    200: V1ListPostCommentsResponse;
};

export type CommentServiceListPostCommentsResponse = CommentServiceListPostCommentsResponses[keyof CommentServiceListPostCommentsResponses];

export type PostServiceSetPostLikeData = {
    body: PostServiceSetPostLikeBody;
    path: {
        post_id: string;
    };
    query?: never;
    url: '/v1/posts/{post_id}/like';
};

export type PostServiceSetPostLikeErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type PostServiceSetPostLikeError = PostServiceSetPostLikeErrors[keyof PostServiceSetPostLikeErrors];

export type PostServiceSetPostLikeResponses = {
    /**
     * A successful response.
     */
    200: V1SetPostLikeResponse;
};

export type PostServiceSetPostLikeResponse = PostServiceSetPostLikeResponses[keyof PostServiceSetPostLikeResponses];

export type ReportServiceListReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 举报类型筛选（可选，不传则返回全部）
         *
         * - REPORT_TYPE_UNSPECIFIED: 未指定
         * - REPORT_TYPE_USER: 举报用户
         * - REPORT_TYPE_POST: 举报帖子
         * - REPORT_TYPE_COMMENT: 举报评论
         * - REPORT_TYPE_REPLY: 举报回复
         */
        type?: 'REPORT_TYPE_UNSPECIFIED' | 'REPORT_TYPE_USER' | 'REPORT_TYPE_POST' | 'REPORT_TYPE_COMMENT' | 'REPORT_TYPE_REPLY';
        /**
         * 举报状态筛选（可选，不传则返回全部）
         *
         * - REPORT_STATUS_UNSPECIFIED: 未指定
         * - REPORT_STATUS_PENDING: 待处理
         * - REPORT_STATUS_PROCESSING: 处理中
         * - REPORT_STATUS_RESOLVED: 已处理（已采纳）
         * - REPORT_STATUS_REJECTED: 已驳回
         */
        status?: 'REPORT_STATUS_UNSPECIFIED' | 'REPORT_STATUS_PENDING' | 'REPORT_STATUS_PROCESSING' | 'REPORT_STATUS_RESOLVED' | 'REPORT_STATUS_REJECTED';
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/reports';
};

export type ReportServiceListReportsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceListReportsError = ReportServiceListReportsErrors[keyof ReportServiceListReportsErrors];

export type ReportServiceListReportsResponses = {
    /**
     * A successful response.
     */
    200: V1ListReportsResponse;
};

export type ReportServiceListReportsResponse = ReportServiceListReportsResponses[keyof ReportServiceListReportsResponses];

export type ReportServiceReportCommentData = {
    body: V1ReportCommentRequest;
    path?: never;
    query?: never;
    url: '/v1/reports/comments';
};

export type ReportServiceReportCommentErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceReportCommentError = ReportServiceReportCommentErrors[keyof ReportServiceReportCommentErrors];

export type ReportServiceReportCommentResponses = {
    /**
     * A successful response.
     */
    200: V1ReportCommentResponse;
};

export type ReportServiceReportCommentResponse = ReportServiceReportCommentResponses[keyof ReportServiceReportCommentResponses];

export type ReportServiceReportPostData = {
    body: V1ReportPostRequest;
    path?: never;
    query?: never;
    url: '/v1/reports/posts';
};

export type ReportServiceReportPostErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceReportPostError = ReportServiceReportPostErrors[keyof ReportServiceReportPostErrors];

export type ReportServiceReportPostResponses = {
    /**
     * A successful response.
     */
    200: V1ReportPostResponse;
};

export type ReportServiceReportPostResponse = ReportServiceReportPostResponses[keyof ReportServiceReportPostResponses];

export type ReportServiceReportUserData = {
    body: V1ReportUserRequest;
    path?: never;
    query?: never;
    url: '/v1/reports/users';
};

export type ReportServiceReportUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceReportUserError = ReportServiceReportUserErrors[keyof ReportServiceReportUserErrors];

export type ReportServiceReportUserResponses = {
    /**
     * A successful response.
     */
    200: V1ReportUserResponse;
};

export type ReportServiceReportUserResponse = ReportServiceReportUserResponses[keyof ReportServiceReportUserResponses];

export type ReportServiceApprovalReportData = {
    body: ReportServiceApprovalReportBody;
    path: {
        /**
         * 举报记录ID
         */
        report_id: string;
    };
    query?: never;
    url: '/v1/reports/{report_id}/approval';
};

export type ReportServiceApprovalReportErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceApprovalReportError = ReportServiceApprovalReportErrors[keyof ReportServiceApprovalReportErrors];

export type ReportServiceApprovalReportResponses = {
    /**
     * A successful response.
     */
    200: V1ApprovalReportResponse;
};

export type ReportServiceApprovalReportResponse = ReportServiceApprovalReportResponses[keyof ReportServiceApprovalReportResponses];

export type ReportServiceListReportEvidenceData = {
    body?: never;
    path: {
        /**
         * 举报记录ID
         */
        report_id: string;
    };
    query?: {
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/reports/{report_id}/evidence';
};

export type ReportServiceListReportEvidenceErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceListReportEvidenceError = ReportServiceListReportEvidenceErrors[keyof ReportServiceListReportEvidenceErrors];

export type ReportServiceListReportEvidenceResponses = {
    /**
     * A successful response.
     */
    200: V1ListReportEvidenceResponse;
};

export type ReportServiceListReportEvidenceResponse = ReportServiceListReportEvidenceResponses[keyof ReportServiceListReportEvidenceResponses];

export type ReportServiceRejectReportData = {
    body: ReportServiceRejectReportBody;
    path: {
        /**
         * 举报记录ID
         */
        report_id: string;
    };
    query?: never;
    url: '/v1/reports/{report_id}/rejection';
};

export type ReportServiceRejectReportErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type ReportServiceRejectReportError = ReportServiceRejectReportErrors[keyof ReportServiceRejectReportErrors];

export type ReportServiceRejectReportResponses = {
    /**
     * A successful response.
     */
    200: V1RejectReportResponse;
};

export type ReportServiceRejectReportResponse = ReportServiceRejectReportResponses[keyof ReportServiceRejectReportResponses];

export type SyncServiceGetActiveDevicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sync/devices';
};

export type SyncServiceGetActiveDevicesErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SyncServiceGetActiveDevicesError = SyncServiceGetActiveDevicesErrors[keyof SyncServiceGetActiveDevicesErrors];

export type SyncServiceGetActiveDevicesResponses = {
    /**
     * A successful response.
     */
    200: V1GetActiveDevicesResponse;
};

export type SyncServiceGetActiveDevicesResponse = SyncServiceGetActiveDevicesResponses[keyof SyncServiceGetActiveDevicesResponses];

export type SyncServiceDisconnectDeviceData = {
    body?: never;
    path: {
        /**
         * 设备 ID
         */
        device_id: string;
    };
    query?: never;
    url: '/v1/sync/devices/{device_id}';
};

export type SyncServiceDisconnectDeviceErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SyncServiceDisconnectDeviceError = SyncServiceDisconnectDeviceErrors[keyof SyncServiceDisconnectDeviceErrors];

export type SyncServiceDisconnectDeviceResponses = {
    /**
     * A successful response.
     */
    200: V1DisconnectDeviceResponse;
};

export type SyncServiceDisconnectDeviceResponse = SyncServiceDisconnectDeviceResponses[keyof SyncServiceDisconnectDeviceResponses];

export type SyncServiceForceSyncData = {
    body: V1ForceSyncRequest;
    path?: never;
    query?: never;
    url: '/v1/sync/force';
};

export type SyncServiceForceSyncErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SyncServiceForceSyncError = SyncServiceForceSyncErrors[keyof SyncServiceForceSyncErrors];

export type SyncServiceForceSyncResponses = {
    /**
     * A successful response.
     */
    200: V1ForceSyncResponse;
};

export type SyncServiceForceSyncResponse = SyncServiceForceSyncResponses[keyof SyncServiceForceSyncResponses];

export type SyncServiceGetSyncStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/sync/status';
};

export type SyncServiceGetSyncStatusErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type SyncServiceGetSyncStatusError = SyncServiceGetSyncStatusErrors[keyof SyncServiceGetSyncStatusErrors];

export type SyncServiceGetSyncStatusResponses = {
    /**
     * A successful response.
     */
    200: V1GetSyncStatusResponse;
};

export type SyncServiceGetSyncStatusResponse = SyncServiceGetSyncStatusResponses[keyof SyncServiceGetSyncStatusResponses];

export type UserServiceGetUserIdByQqData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * QQ 号
         */
        qq_number?: string;
    };
    url: '/v1/users/id_by_qq';
};

export type UserServiceGetUserIdByQqErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetUserIdByQqError = UserServiceGetUserIdByQqErrors[keyof UserServiceGetUserIdByQqErrors];

export type UserServiceGetUserIdByQqResponses = {
    /**
     * A successful response.
     */
    200: V1GetUserIdByQqResponse;
};

export type UserServiceGetUserIdByQqResponse = UserServiceGetUserIdByQqResponses[keyof UserServiceGetUserIdByQqResponses];

export type UserServiceGetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me';
};

export type UserServiceGetMeErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetMeError = UserServiceGetMeErrors[keyof UserServiceGetMeErrors];

export type UserServiceGetMeResponses = {
    /**
     * A successful response.
     */
    200: V1GetMeResponse;
};

export type UserServiceGetMeResponse = UserServiceGetMeResponses[keyof UserServiceGetMeResponses];

export type UserServiceChangeAvatarData = {
    body: V1ChangeAvatarRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/avatar';
};

export type UserServiceChangeAvatarErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceChangeAvatarError = UserServiceChangeAvatarErrors[keyof UserServiceChangeAvatarErrors];

export type UserServiceChangeAvatarResponses = {
    /**
     * A successful response.
     */
    200: V1ChangeAvatarResponse;
};

export type UserServiceChangeAvatarResponse = UserServiceChangeAvatarResponses[keyof UserServiceChangeAvatarResponses];

export type UserServiceModifyDepartmentsData = {
    body: V1ModifyDepartmentsRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/departments';
};

export type UserServiceModifyDepartmentsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceModifyDepartmentsError = UserServiceModifyDepartmentsErrors[keyof UserServiceModifyDepartmentsErrors];

export type UserServiceModifyDepartmentsResponses = {
    /**
     * A successful response.
     */
    200: V1ModifyDepartmentsResponse;
};

export type UserServiceModifyDepartmentsResponse = UserServiceModifyDepartmentsResponses[keyof UserServiceModifyDepartmentsResponses];

export type UserServiceEditLinksData = {
    body: V1EditLinksRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/links';
};

export type UserServiceEditLinksErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceEditLinksError = UserServiceEditLinksErrors[keyof UserServiceEditLinksErrors];

export type UserServiceEditLinksResponses = {
    /**
     * A successful response.
     */
    200: V1EditLinksResponse;
};

export type UserServiceEditLinksResponse = UserServiceEditLinksResponses[keyof UserServiceEditLinksResponses];

export type UserServiceChangeNameData = {
    body: V1ChangeNameRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/name';
};

export type UserServiceChangeNameErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceChangeNameError = UserServiceChangeNameErrors[keyof UserServiceChangeNameErrors];

export type UserServiceChangeNameResponses = {
    /**
     * A successful response.
     */
    200: V1ChangeNameResponse;
};

export type UserServiceChangeNameResponse = UserServiceChangeNameResponses[keyof UserServiceChangeNameResponses];

export type UserServiceUpdateSettingsData = {
    body: V1UpdateSettingsRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/settings';
};

export type UserServiceUpdateSettingsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceUpdateSettingsError = UserServiceUpdateSettingsErrors[keyof UserServiceUpdateSettingsErrors];

export type UserServiceUpdateSettingsResponses = {
    /**
     * A successful response.
     */
    200: V1UpdateSettingsResponse;
};

export type UserServiceUpdateSettingsResponse = UserServiceUpdateSettingsResponses[keyof UserServiceUpdateSettingsResponses];

export type UserServiceGetMyVerificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users/me/verification';
};

export type UserServiceGetMyVerificationErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetMyVerificationError = UserServiceGetMyVerificationErrors[keyof UserServiceGetMyVerificationErrors];

export type UserServiceGetMyVerificationResponses = {
    /**
     * A successful response.
     */
    200: V1GetMyVerificationResponse;
};

export type UserServiceGetMyVerificationResponse = UserServiceGetMyVerificationResponses[keyof UserServiceGetMyVerificationResponses];

export type UserServiceApplyVerificationData = {
    body: V1ApplyVerificationRequest;
    path?: never;
    query?: never;
    url: '/v1/users/me/verification';
};

export type UserServiceApplyVerificationErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceApplyVerificationError = UserServiceApplyVerificationErrors[keyof UserServiceApplyVerificationErrors];

export type UserServiceApplyVerificationResponses = {
    /**
     * A successful response.
     */
    200: V1ApplyVerificationResponse;
};

export type UserServiceApplyVerificationResponse = UserServiceApplyVerificationResponses[keyof UserServiceApplyVerificationResponses];

export type UserServiceSetFollowData = {
    body: UserServiceSetFollowBody;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/me/{user_id}/follow';
};

export type UserServiceSetFollowErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceSetFollowError = UserServiceSetFollowErrors[keyof UserServiceSetFollowErrors];

export type UserServiceSetFollowResponses = {
    /**
     * A successful response.
     */
    200: V1SetFollowResponse;
};

export type UserServiceSetFollowResponse = UserServiceSetFollowResponses[keyof UserServiceSetFollowResponses];

export type UserServiceGetUserData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}';
};

export type UserServiceGetUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceGetUserError = UserServiceGetUserErrors[keyof UserServiceGetUserErrors];

export type UserServiceGetUserResponses = {
    /**
     * A successful response.
     */
    200: V1GetUserResponse;
};

export type UserServiceGetUserResponse = UserServiceGetUserResponses[keyof UserServiceGetUserResponses];

export type UserServiceListUserCollectedPostsData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/collected_posts';
};

export type UserServiceListUserCollectedPostsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserCollectedPostsError = UserServiceListUserCollectedPostsErrors[keyof UserServiceListUserCollectedPostsErrors];

export type UserServiceListUserCollectedPostsResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserPostsResponse;
};

export type UserServiceListUserCollectedPostsResponse = UserServiceListUserCollectedPostsResponses[keyof UserServiceListUserCollectedPostsResponses];

export type UserServiceListUserFollowersData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型：下拉刷新（返回最新数据）/上拉加载更多（返回历史数据）
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/followers';
};

export type UserServiceListUserFollowersErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserFollowersError = UserServiceListUserFollowersErrors[keyof UserServiceListUserFollowersErrors];

export type UserServiceListUserFollowersResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserRelatedResponse;
};

export type UserServiceListUserFollowersResponse = UserServiceListUserFollowersResponses[keyof UserServiceListUserFollowersResponses];

export type UserServiceListUserFollowingsData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型：下拉刷新（返回最新数据）/上拉加载更多（返回历史数据）
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/followings';
};

export type UserServiceListUserFollowingsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserFollowingsError = UserServiceListUserFollowingsErrors[keyof UserServiceListUserFollowingsErrors];

export type UserServiceListUserFollowingsResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserRelatedResponse;
};

export type UserServiceListUserFollowingsResponse = UserServiceListUserFollowingsResponses[keyof UserServiceListUserFollowingsResponses];

export type UserServiceListUserLikedPostsData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/liked_posts';
};

export type UserServiceListUserLikedPostsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserLikedPostsError = UserServiceListUserLikedPostsErrors[keyof UserServiceListUserLikedPostsErrors];

export type UserServiceListUserLikedPostsResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserPostsResponse;
};

export type UserServiceListUserLikedPostsResponse = UserServiceListUserLikedPostsResponses[keyof UserServiceListUserLikedPostsResponses];

export type UserServiceListUserMutualFollowersData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型：下拉刷新（返回最新数据）/上拉加载更多（返回历史数据）
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/mutual_followers';
};

export type UserServiceListUserMutualFollowersErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserMutualFollowersError = UserServiceListUserMutualFollowersErrors[keyof UserServiceListUserMutualFollowersErrors];

export type UserServiceListUserMutualFollowersResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserRelatedResponse;
};

export type UserServiceListUserMutualFollowersResponse = UserServiceListUserMutualFollowersResponses[keyof UserServiceListUserMutualFollowersResponses];

export type UserServiceListUserPostsData = {
    body?: never;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: {
        /**
         * 刷新类型
         *
         * - REFRESH_TYPE_PULL_DOWN: 下拉刷新，获取最新数据
         * - REFRESH_TYPE_PULL_UP: 上拉加载，获取历史数据
         */
        refresh_type?: 'REFRESH_TYPE_UNSPECIFIED' | 'REFRESH_TYPE_PULL_DOWN' | 'REFRESH_TYPE_PULL_UP';
        /**
         * 关键词搜索
         */
        'filter.keyword'?: string;
        /**
         * 需要返回的帖子数量
         */
        'pagination.need_num'?: number;
        /**
         * 游标分数、时间戳或其他标识符，用于推荐、热度、时间排序的瀑布流分页加载。
         * 游标分数：用于推荐/热度算法的分页加载，表示上次返回结果中的最后一项的分数
         * 游标时间戳：用于时间排序的分页加载，表示上次返回结果中的最后一项的发布时间
         *
         * 为空则说明是首次请求第一页数据
         */
        'pagination.cursor'?: string;
    };
    url: '/v1/users/{user_id}/posts';
};

export type UserServiceListUserPostsErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceListUserPostsError = UserServiceListUserPostsErrors[keyof UserServiceListUserPostsErrors];

export type UserServiceListUserPostsResponses = {
    /**
     * A successful response.
     */
    200: V1ListUserPostsResponse;
};

export type UserServiceListUserPostsResponse = UserServiceListUserPostsResponses[keyof UserServiceListUserPostsResponses];

export type UserServiceChangeRemarkData = {
    body: UserServiceChangeRemarkBody;
    path: {
        /**
         * 目标用户ID
         */
        user_id: string;
    };
    query?: never;
    url: '/v1/users/{user_id}/remark';
};

export type UserServiceChangeRemarkErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type UserServiceChangeRemarkError = UserServiceChangeRemarkErrors[keyof UserServiceChangeRemarkErrors];

export type UserServiceChangeRemarkResponses = {
    /**
     * A successful response.
     */
    200: V1ChangeRemarkResponse;
};

export type UserServiceChangeRemarkResponse = UserServiceChangeRemarkResponses[keyof UserServiceChangeRemarkResponses];
