// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"app.shiningacg.club/config"
	"app.shiningacg.club/internal/biz"
	"app.shiningacg.club/internal/repo"
	"app.shiningacg.club/internal/service"
	"app.shiningacg.club/pkg/ffmpeg"
	"app.shiningacg.club/pkg/s3"
	"github.com/bwmarrin/snowflake"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序依赖
func InitializeApp(cfg *config.Config) (*App, func(), error) {
	db, err := repo.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	resourceRepoImpl := repo.NewResourceRepo(db)
	client, err := NewS3Client(cfg)
	if err != nil {
		return nil, nil, err
	}
	node, err := NewSnowflakeNode(cfg)
	if err != nil {
		return nil, nil, err
	}
	workerPool, err := NewFFmpegWorkerPool(cfg)
	if err != nil {
		return nil, nil, err
	}
	resourceUseCase := biz.NewResourceUseCase(resourceRepoImpl, client, node, workerPool)
	resourceServiceServer := service.NewResourceServiceServer(resourceUseCase)
	app, err := NewApp(cfg, resourceServiceServer, workerPool)
	if err != nil {
		return nil, nil, err
	}
	return app, func() {
	}, nil
}

// wire.go:

// DataProviderSet 数据层依赖注入集合
var DataProviderSet = wire.NewSet(repo.NewDB, repo.NewResourceRepo, wire.Bind(new(repo.ResourceRepo), new(*repo.ResourceRepoImpl)))

// BizProviderSet 业务逻辑层依赖注入集合
var BizProviderSet = wire.NewSet(biz.NewResourceUseCase)

// ServiceProviderSet 服务层依赖注入集合
var ServiceProviderSet = wire.NewSet(service.NewResourceServiceServer)

// SnowflakeProvider 雪花算法节点提供者
func NewSnowflakeNode(cfg *config.Config) (*snowflake.Node, error) {
	return snowflake.NewNode(cfg.Snowflake.NodeID)
}

// S3ClientProvider S3 客户端提供者
func NewS3Client(cfg *config.Config) (*s3.Client, error) {
	return s3.NewClient(
		cfg.OSS.Endpoint,
		cfg.OSS.AccessKey,
		cfg.OSS.SecretKey,
		cfg.OSS.Bucket,
		cfg.OSS.UseSSL,
	)
}

// FFmpegWorkerPoolProvider FFmpeg 工作池提供者
func NewFFmpegWorkerPool(cfg *config.Config) (*ffmpeg.WorkerPool, error) {
	pool := ffmpeg.NewWorkerPool(cfg.FFmpeg.MaxWorkers, cfg.FFmpeg.QueueSize)
	pool.Start()
	return pool, nil
}
